name: black-formatting
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Black
        run: pip install black

      - name: Run Black Check
        run: black --check .